### ISSUE TITLE
Huh?

### ISSUE THREAD

**Issue by kcstarr** [serv-inc/safe-search#1]
Ur app (ext) is poorly described. The support link to GitHub has little information on it. There r no reviews. What's w all that?

**Comment by serv-inc** [comment]
Hi kcstarr. The app has not yet solicited feedback/reviews. In fact, there is no screen to remind users that feedback is appreciated. What kind of documentation would you like?

**Comment by serv-inc** [comment]
Closed: there is now a minimal wiki. Just comment on what info you would like if you want to have it reopened.
