### ISSUE TITLE
How to preset settings?

### ISSUE THREAD

**Issue by marcogaio** [serv-inc/safe-search#10]
I'm installing in my organization your wonderful addon, on FireFox 60 ESR.

I wan to 'preset' for users the youtube strictness level, but seems that option are not saved on prefs (about:preferences) and so i don't know how to preset it via '.js' prefs file.

Can yiu give me some hint? Thanks.

**Comment by marcogaio** [comment]
I've see https://github.com/serv-inc/safe-search/wiki/Configure page, but speaks about Chrome only.

**Comment by serv-inc** [comment]
It has not been answered yet [on superuser.com](https://superuser.com/questions/1303910/translate-google-chromes-storage-from-policies-managed-json-to-firefox). Would you like me to post a bounty, or do you have any suggestions on how to do this?

**Comment by serv-inc** [comment]
It has been solved at superuser: https://superuser.com/questions/1303910/translate-google-chromes-storage-from-policies-managed-json-to-firefox. If you would like further instructions, please say so.

**Comment by marcogaio** [comment]
Ahem, sorry but i've not understood.

Seems to me that you have to modify your extensions, but after that it is not clear to me how and where save the settings file.

Can you provide an example? Thanks.

**Comment by serv-inc** [comment]
Please have a look at [the updated wiki](https://github.com/serv-inc/safe-search/wiki/Configure). If there is anything missing, feel welcome to reopen.
