### ISSUE TITLE
Remove same param from uri (solution included)

### ISSUE THREAD

**Issue by sfrauenfelder** [serv-inc/safe-search#11]
In the function _add_if_neccesary there is a to do:
   // todo: should also remove same param, (and maybe add & *or* ? depending)
This function solves the to do (tested in Firefox Quantum 62.0.3 (64 bit), duckduckgo).
`function _add_or_replace(uri, par, val) {`
`    var f = '((\\?)' + par + '=[^&]+&|&' + par + '=[^&]+)';`
`    var t = uri.replace(new RegExp(f, 'gi'), '\$2');`
`    return t + '&' + par + '=' + val;`
`}`
It first sets up a regular expression f, then replaces the par=val with nothing, effectively removing the parameter. Then it adds the required par=val.
The regular expression matches
- either "par=val&" directly after the question mark: (\\?)' + par + '=[^&]+&
- or "par=val" after an ampersand: &' + par + '=[^&]+

The replace function pastes back the question mark (\\$2) if the first case was matched.
Hope this helps!

**Comment by serv-inc** [comment]
Good inspiration to do this. The code failed for me. If you want to try it again, you could use the following test in AddonSpec.js inside the main braces.

```javascript
  describe("should clean duplicate parameters (inside _a_o_r)", function() {
    it("for Google", function() {
      let uri = "http://google.de/search?q=test&safe=vss";
      
      expect(_add_or_replace(_add_or_replace(uri, "safe", "active"), "ssui", "on")).toEqual(
        "http://google.de/search?q=test&safe=active&ssui=on");
    });
  });
```

Still, it should be working now. Awesome that you added code.

**Comment by serv-inc** [comment]
Reopened as I broke Firefox. Feel welcome to submit a pull request.

**Comment by sfrauenfelder** [comment]
With 4.2.1, it is still possible to fool the add-on. With duckduckgo, if I add "&kp=-2" to the end of the url, that param-value combination is kept and the undesired results returned.
Supppose I have
`https://duckduckgo.com/?q=test&t=h_&kp=1&ia=web`
then change it to
`https://duckduckgo.com/?q=test&t=h_&kp=1&ia=web&kp=-2`
and go, then this is the resulting url, and undesired search results are displayed:
`https://duckduckgo.com/?q=test&t=h_&kp=-2&ia=web`

I guess the add-on searches/replaces only one occurence of par=val?

I can't do this with google though.
