### ISSUE TITLE
4.2.0 now makes both google and duckduckgo fail to show any results

### ISSUE THREAD

**Issue by MightyPork** [serv-inc/safe-search#12]
![screenshot_20181005_090447](https://user-images.githubusercontent.com/2041118/46520844-c36d7d80-c87d-11e8-888b-776c08f1233b.png)

It also broke google translate. Disabling the extension immediately fixes it for me. I might as well leave it disabled if it's gonna break my browser after every other update :p

**Comment by serv-inc** [comment]
Please forgive me. 4.2.0 was disabled. It worked on Chrome, but should probably have been tested on FF as well.

**Comment by serv-inc** [comment]
Argh, I was stupid. Lesson: **ALWAYS** test for FF as well. Again, it was awesome that you reported this so quickly.

**Comment by MightyPork** [comment]
I'm a bit curious how [this](https://github.com/serv-inc/safe-search/commit/1afb722f3d41a7932c819e93d0a8930e9af522e1#diff-354722d756450516a8aa3c287f704a33L77) could work in chrome, anyway can confirm the update fixed it.
