### ISSUE TITLE
google drive problems

### ISSUE THREAD

**Issue by allstarleb** [serv-inc/safe-search#13]
When i disable the plugin, my drive loads fine, when i enable it my drive doesn't load very well. Any idea how to fix this? Maybe if there is a way to enable "exceptions" on google drive that could help.

**Comment by serv-inc** [comment]
Are you using the current version? There was a problem with versions prior to 4.1.2. See https://github.com/serv-inc/safe-search/issues/9.

**Comment by allstarleb** [comment]
Hello, i am using latest version, version 4.2.2. The problem in more detail is when I am in chrome and using google drive, it takes a very long time to load and most of the time doesn't load. The only way I can make it load is by disabling the plugin and it works....

**Comment by serv-inc** [comment]
Awesome that you reported this. #9 only fixed google docs. Please report back if the problem persists.

**Comment by allstarleb** [comment]
The problem isn't fixed, I don't think you read my response properly. It doesn't work still l have to disable the plugin for things to work...

**Comment by serv-inc** [comment]
My response was unclear: there is a new version 4.2.3 (and 4.3.0) as of today that should fix this problem. I did not experience the problem myself, as I had not used Google Drive before. But from your comment, it seems that the new versions did not fix the problem. Let me start a Google Drive session to dig deeper. Does this occur for any type of file, etc?

**Comment by serv-inc** [comment]
Awesome. Thanks for reporting back.
