### ISSUE TITLE
4.3.1 makes browser console appears whenever youtube is opened

### ISSUE THREAD

**Issue by TheFifthHorsemen** [serv-inc/safe-search#16]
Upon starting firefox, the first time youtube is opened the browser console will open up. It will not reappear until firefox is fully closed and opened again.

It looks like it has to do with the alerts added on lines 87, 88, and 104 of `addon/background.js` as these were changed in commit 289cd66bf1ef3b81671c1b72069dc96a00e87ceb but I may be wrong about this

**Comment by orbitalchicken** [comment]
I have the same problem. It happen only with 4.3.1. It does not happen with 4.3.0.
