### ISSUE TITLE
Safe-search ignores search queries in Duckduckgo when option "GET requests" is set to Off (--> POST)

### ISSUE THREAD

**Issue by sfrauenfelder** [serv-inc/safe-search#17]
Duckduckgo has a privacy setting for using GET or POST requests, and if set to Off/POST, the safe-search add-on has no effect. This gives browser users a very simple way to circumvent the add-on.

I think it is required that the add-on works for POST requests too.

The setting is found under Other Settings > Privacy > "GET requests" (Windows) or "Requests shown in url" (Android).
![afbeelding](https://user-images.githubusercontent.com/42144635/51835290-474fe780-22fd-11e9-877b-f94f181626ea.png)

**Comment by serv-inc** [comment]
Thank you for pointing this out. As of https://stackoverflow.com/questions/21220806/chrome-extension-modify-formdata#21228662, it's not possible to use the current technique. So for now POST requests are disabled. If you wish to use them, continue on this issue.
