### ISSUE TITLE
password

### ISSUE THREAD

**Issue by jim6565** [serv-inc/safe-search#2]
no password protection so easily disabled :(

**Comment by serv-inc** [comment]
Hi @jim6565, thanks for the feedback. Which browser and OS are you using? (If chrome and windows, have a look at https://productforums.google.com/forum/#!topic/chrome/bKoAAPX4iVA)

**Comment by serv-inc** [comment]
Seems like this is a bit hard to do programmatically. There's now a wiki entry for Chrome on Linux. If you use another combination, just say what you're using to reopen the issue.
