### ISSUE TITLE
Vimeo filter should be more flexible

### ISSUE THREAD

**Issue by amzaf** [serv-inc/safe-search#22]
The Vimeo filter, as it stands right now, disables the submit button on the mature content dialog, so that the user cannot change settings. 

Its chief drawback is that it does not allow the user to enforce stricter settings such as disabling sexually suggestive content, profanities, or disabling mature content all together.

 The filter only hides nudity.

**Comment by serv-inc** [comment]
Should be fixed: a minimum of nudity is enforced, other things can be set by hand in Vimeo. If you require more (say, configurability like YouTube), feel welcome to create a new issue.
