### ISSUE TITLE
Google search page loads twice on Chrome

### ISSUE THREAD

**Issue by amzaf** [serv-inc/safe-search#24]
When the extension is enabled, the google result page for a search term appears to load twice. It looks like the extension triggers a postback right after the page is loaded. The behavior can easily be observed by repeating several searches and toggling the extension on and off for comparison.
I can reproduce this on the latest version of Chrome browser and Safe Search version 5.

**Comment by serv-inc** [comment]
Thanks! Please report if 5.1.0 does not fix it. (It's still active for duckduckgo, because I could not find another way to safely block)

**Comment by amzaf** [comment]
Fixed. Thanks!

**Comment by TangoCharlie4** [comment]
I uninstalled all the Chrome extensions and it resolved my problem.

**Comment by shubhamparkhe31** [comment]
> When the extension is enabled, the google result page for a search term appears to load twice. It looks like the extension triggers a postback right after the page is loaded. The behavior can easily b

**Comment by shubhamparkhe31** [comment]
thanx. i set access of extensions on 'when click it'. it's changing information on site.
