### ISSUE TITLE
One more mode for youtube ?

### ISSUE THREAD

**Issue by orbitalchicken** [serv-inc/safe-search#25]
Youtube "Under 18" mode is not really "under 18" since, as a user, I can login with a google account and just set my age to be over 18 (even if I am not really over 18). So, do you think it would be possible to add a mode which is "really" under 18. I mean it would only allow all content which is not "over 18" (it is more content than the moderate mode), and **always** block the "over 18" content enven when I am logged in with a faked 18+ account ?

**Comment by serv-inc** [comment]
That's what the under 18 mode is supposed to do. Let me see how to fix.

**Comment by serv-inc** [comment]
Cookies seem to be identical in both modes. The only way that worked was to log the user out. So this is what 6.1.0 does. Feel welcome to comment or reopen if this does not work for you.

**Comment by slorrain** [comment]
Under 18 mode is now working perfectly (user is logged out) ! Thank you. 
But can you leave a 4th option "Allowed (no filtering)" ?

**Comment by orbitalchicken** [comment]
"Under 18" mode is now working perfectly (user is logged out) ! Thank you.
But can you leave a 4th option "Allowed (no filtering)" ?
