### ISSUE TITLE
Add other websites

### ISSUE THREAD

**Issue by hllwdfr** [serv-inc/safe-search#3]
Could you please add dailymotion.com ? Thank you!

**Comment by serv-inc** [comment]
Could you rank the importance of the items for you:

- the above could take a day or two
- showing the score a day or two as well
- showing another page as the blockpage one to four days
- password-protecting the options page three to ten days
- adding toggles for YouTube (not by you, but an issue for safe-search) three to five days

**Comment by hllwdfr** [comment]
Ok. I added number #3: performance. Here is the order I suggest:
    
      1) showing another page (would be an option) as the blockpage
        one to four days.
      2) password-protecting the options page three to ten days.
      3) performance: show the blocking page faster, as soon as the
        score is reach + tweeks detailled below.
      
      4) showing the score a day or two as well.
      5) add dailymotion.com to "enforce safe-search" a day or two
        (not the same extension).
      6) adding toggles for YouTube (not by you, but an issue for
        safe-search) three to five days.
      
    
    Note: all for "Web Site Filter" except #5.
    By the way, showing the score (4) would not be relevant if the
      performance is fixed (3): 
    
    For (3) performance, I suggest the following: 
    
    
      3.1) show the blocking page as soon as the score is reached.
      3.2) loop into the keywords in reverse order (from higher
        scrores to lower scores)
      3.3) use for loops instead of Array functions. REF:
https://hackernoon.com/javascript-performance-test-for-vs-for-each-vs-map-reduce-filter-find-32c1113f19d7
    
    Performance is important to avoid the "not for kids" page being
      shown to many seconds: to user can press ESC during this delay. I
      don't know if "ESC" keypress could be catched and ignored.
    
    Question: 
    1) what would be the " toggles for YouTube" ? 
    
    
    Le 2018-08-09 à 18:51, serv-inc a
      écrit :
    
    
      
      Could you rank the importance of the items for you:
      
        the above could take a day or two
        showing the score a day or two as well
        showing another page as the blockpage one to four days
        password-protecting the options page three to ten days
        adding toggles for YouTube (not by you, but an issue for
          safe-search) three to five days
      
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or mute the thread.
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/serv-inc/safe-search","title":"serv-inc/safe-search","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/serv-inc/safe-search"}},"updates":{"snippets":[{"icon":"PERSON","message":"@serv-inc in #3: Could you rank the importance of the items for you:\r\n\r\n- the above could take a day or two\r\n- showing the score a day or two as well\r\n- showing another page as the blockpage one to four days\r\n- password-protecting the options page three to ten days\r\n- adding toggles for YouTube (not by you, but an issue for safe-search) three to five days"}],"action":{"name":"View Issue","url":"https://github.com/serv-inc/safe-search/issues/3#issuecomment-411922905"}}}
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/serv-inc/safe-search/issues/3#issuecomment-411922905",
"url": "https://github.com/serv-inc/safe-search/issues/3#issuecomment-411922905",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [serv-inc/safe-search] Add other websites (#3)",
"sections": [
{
"text": "",
"activityTitle": "**serv-inc**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@serv-inc",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"serv-inc/safe-search\",\n\"issueId\": 3,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"serv-inc/safe-search\",\n\"issueId\": 3\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/serv-inc/safe-search/issues/3#issuecomment-411922905"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 366108347\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by serv-inc** [comment]
>  Question:
>     1) what would be the " toggles for YouTube" ?
> 

See issue #4

**Comment by hllwdfr** [comment]
Hello, 
    
    Another tweek I would do: 
    
    When looping through the keywords, as soon as the score is
      greather then a really low minimum trigger (say 5), 
      add a css rule on the <body> :   visibility = hidden; 
    
    Then, when the loop is fihished, if the score did no bump the
      upper limit, just reset the visibility (visibility = "" will reset
      it to it's default value) ;
    
    This will prevent the display of unwanted images during the parsing
    / score calculation. 
    
    
    Le 2018-08-10 à 00:17, Stéphane Lorrain
      a écrit :
    
    
      
      Ok. I added number #3: performance. Here is the order I suggest:
      
        1) showing another page (would be an option) as the
          blockpage one to four days.
        2) password-protecting the options page three to ten days.
        3) performance: show the blocking page faster, as soon as
          the score is reach + tweeks detailled below.
        
        4) showing the score a day or two as well.
        5) add dailymotion.com to "enforce safe-search" a day or two
          (not the same extension).
        6) adding toggles for YouTube (not by you, but an issue for
          safe-search) three to five days.
        
      
      Note: all for "Web Site Filter" except #5.
      By the way, showing the score (4) would not be relevant if the
        performance is fixed (3): 
      
      For (3) performance, I suggest the following: 
      
      
        3.1) show the blocking page as soon as the score is reached.
        3.2) loop into the keywords in reverse order (from higher
          scrores to lower scores)
        3.3) use for loops instead of Array functions. REF:
          https://hackernoon.com/javascript-performance-test-for-vs-for-each-vs-map-reduce-filter-find-32c1113f19d7
      
      Performance is important to avoid the "not for kids" page being
        shown to many seconds: to user can press ESC during this delay.
        I don't know if "ESC" keypress could be catched and ignored.
      
      Question: 
      1) what would be the " toggles for YouTube" ? 
      
      
      Le 2018-08-09 à 18:51, serv-inc a
        écrit :
      
      
        
        Could you rank the importance of the items for you:
        
          the above could take a day or two
          showing the score a day or two as well
          showing another page as the blockpage one to four days
          password-protecting the options page three to ten days
          adding toggles for YouTube (not by you, but an issue for
            safe-search) three to five days
        
        —
          You are receiving this because you authored the thread.
          Reply to this email directly, view it on GitHub, or mute the thread.
        {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/serv-inc/safe-search","title":"serv-inc/safe-search","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/serv-inc/safe-search"}},"updates":{"snippets":[{"icon":"PERSON","message":"@serv-inc in #3: Could you rank the importance of the items for you:\r\n\r\n- the above could take a day or two\r\n- showing the score a day or two as well\r\n- showing another page as the blockpage one to four days\r\n- password-protecting the options page three to ten days\r\n- adding toggles for YouTube (not by you, but an issue for safe-search) three to five days"}],"action":{"name":"View Issue","url":"https://github.com/serv-inc/safe-search/issues/3#issuecomment-411922905"}}}
        [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/serv-inc/safe-search/issues/3#issuecomment-411922905",
"url": "https://github.com/serv-inc/safe-search/issues/3#issuecomment-411922905",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [serv-inc/safe-search] Add other websites (#3)",
"sections": [
{
"text": "",
"activityTitle": "**serv-inc**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@serv-inc",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"serv-inc/safe-search\",\n\"issueId\": 3,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"serv-inc/safe-search\",\n\"issueId\": 3\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/serv-inc/safe-search/issues/3#issuecomment-411922905"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 366108347\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by serv-inc** [comment]
Salut,

while the image blocking should be possible (maybe just hiding the images would be acceptable to you, too?), you could also have a look at https://github.com/serv-inc/blacklist. It blocks the main adult sites by default. So your kids would be hard-pressed to find some sites where they could look at stuff. This could also get some nicer blockpage etc.

**Comment by serv-inc** [comment]
Salut,

have a look at the performance in version 1.4.0.
