### ISSUE TITLE
Please add OneSearch.com

### ISSUE THREAD

**Issue by jawad-lotfi** [serv-inc/safe-search#31]
Hello,  I have left a similar request on the Firefox AddOns page to which you answered by asking how safesearch is enforced without the add on.
I tried searching with all 3 filters and compared the urls and here's what I found:
In the url of the search result, there is a vm parameter that can have 3 values. I found out that vm=r is strict, vm=i is moderate and vm=p is off.

After looking at your code I noticed that it looks like the following setting in background.js :
```
else if ( /search.yahoo.*\/search/.test(uri) ) {
    return _meta_add(uri, ["vm"], ["r"]);
```
I'm thinking that the fix is really just a duplicate of the one above but for onesearch.com.

Again, thanks for this very useful add-on!

**Comment by serv-inc** [comment]
Thanks for the MR. It should be live for Firefox.
