### ISSUE TITLE
Firefox: Turn off Youtube Restricted mode

### ISSUE THREAD

**Issue by IgorArnaut** [serv-inc/safe-search#39]
Please add an option to turn of just Youtube Restricted mode. Some videos are restricted, despite being not NSFW.

Browser: Firefox
OS: Windows 10 64-bit

**Comment by IgorArnaut** [comment]
Anyone???

**Comment by serv-inc** [comment]
Feel welcome to submit a pull request. It is not the current focus.
Am 20.06.2021 20:37 schrieb "Igor" ***@***.***>:

**Comment by iliadaili** [comment]
I came to ask for the same thing, I'd appreciate very much the addition of a fourth option that completely disables the restrictions for YouTube.

**Comment by serv-inc** [comment]
should be implemented, it just needs to be published
