### ISSUE TITLE
Wiki for macOS 

### ISSUE THREAD

**Issue by Gandulf78** [serv-inc/safe-search#42]
Hi. 
I am in the process of deploying the extension on Mac with Firefox. Would you have a wiki for that too? Thank you.

**Comment by serv-inc** [comment]
Hi,
did the Linux guide help you ? Would you recommend additional info ?

**Comment by Gandulf78** [comment]
Hi. 
I used the Mozilla guidance https://support.mozilla.org/en-US/kb/customizing-firefox-macos-using-configuration-prof
with the following org.mozilla.firefox.plist file:

> <?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>EnterprisePoliciesEnabled</key>
	<true/>
	  <key>DNSOverHTTPS</key>
	  <dict>
	    <key>Enabled</key>
	    <false/>
	    <key>Locked</key>
	    <true/>
	</dict>
	<key>DisablePrivateBrowsing</key>
	  <true/>
	  <key>Extensions</key>
	    <dict>
	      <key>Install</key>
	      <array>
	        <string>https://addons.mozilla.org/firefox/downloads/latest/sas/</string>
	      </array>
	      <key>Locked</key>
	      <array>
	        <string>{b52acdad-e4a6-44da-afc9-9bd22572db99}</string>
	      </array>
	    </dict>	 		
	  <key>DisableSafeMode</key>
	  <true/>
	  
	  <key>3rdparty</key>
	      <dict>
	        <key>Extensions</key>
	        <dict>
	          <key>{b52acdad-e4a6-44da-afc9-9bd22572db99}</key>
	          <dict>
	            <key>youtube</key>
	            <integer>1</integer>
	          </dict>
	        </dict>
	      </dict>
	  
    <key>Proxy</key>
    <dict>
      <key>Mode</key>
      <string>system</string>
      <key>Locked</key>
      <true/> 
    </dict>
</dict>
</plist>
