### ISSUE TITLE
Youtube issues

### ISSUE THREAD

**Issue by Catarax** [serv-inc/safe-search#7]
Youtube comments are broken in most of videos, restraint mode
 "Les commentaires de cette vidéo sont masqués, car cette dernière est en mode restreint."

And some video ask me to have a Google app account (and i'm logged in).

When I disable the extension, everything is good, I thought it was my tampermonkey messing it.

Using https://www.youtube.com.

**Comment by serv-inc** [comment]
> Youtube comments are broken in most of videos, restraint mode
[...]
> And some video ask me to have a Google app account (and i'm logged in).

This is done by YouTube in restricted mode (mode restreint). To enable "lenient mode", click on the icon, select "Options", and set "YouTube-strictness" to "lenient". That only blocks adult content. 

C'est le defaut choisi par YouTube. Vous pourriez desactiver cette protection dans la page des options. Le mode "lenient" seulement bloque les videos adultes.

**Comment by serv-inc** [comment]
PS: Would it help if the "please log in" message were replaced with a special message that the extension blocks this video?

**Comment by Catarax** [comment]
Thanks, i never went to the options of the extension, yes a custom message would be better, youtube was confusing me or maybe you should set the lenient mode by default i think.

**Comment by serv-inc** [comment]
The option was added three days ago, so you could not have used it before. Good that the option works for you.

**Comment by serv-inc** [comment]
UI change issue: #8
