### ISSUE TITLE
Extension breaks Google Docs & Google Sheets in Firefox

### ISSUE THREAD

**Issue by talljosh** [serv-inc/safe-search#9]
As of the past few weeks, Google Docs and Google Sheets will load a document but then sit with a message saying "Trying to connect..." forever. Disabling this Enforce SafeSearch extension resolves the issue.

I'm running Firefox 62.0 on Ubuntu 18.04.

**Comment by serv-inc** [comment]
Could you please double-check if the update to 4.1.2 fixes this for you?

**Comment by serv-inc** [comment]
Seems like it's fixed. Reply if the problem persists.

**Comment by talljosh** [comment]
Yep, that seems to fix it.

**Comment by serv-inc** [comment]
It was helpful that you confirmed this.
